### PR TITLE
Power plant

### PR DESCRIPTION
**Pull request by cledna**
Pull request for small update to water.pplnt module and preliminary test code for pplnt.py.

### CODE REVIEW

**Comment by rplzzz** [comment]
I will pull this branch and test it later this evening.  There are a few odds and ends to clean up, but we should be able to merge it today or tomorrow.

**Comment by rplzzz** [comment]
@cledna, when we run the test on the gcam queries, where do we actually run the GCAM query?  The only occurrence in `gcquery-test.py` of the string `gcam_query` is commented out.  Can you explain how these tests are supposed to work?

**Comment by cledna** [comment]
Hi Robert, 
util.gcam_query is where we run the queries. I commented it out because I was working on other portions of the code and didn't want to rerun it every time, but it should not be commented out in the final version.

**Comment by rplzzz** [comment]
And should the files in `src/gcam/test/sample-out` be committed to the repository?  It looks like some are and some aren't, but I'm not clear on the intended use.

**Comment by cledna** [comment]
It doesn't matter; all of the files are generated by functions in gcquery-test.py.

**Comment by rplzzz** [comment]
If the files are meant to be generated by functions in gcquery-test.py, then they _shouldn't_ be committed.  If you commit them, then if gcquery-test.py fails to generate them for some reason, you won't be able to tell.

**Comment by rplzzz** [comment]
@cledna Did we ever resolve the questions above about how this should work?  I'd like to get this branch disposed of if we can.

**Comment by rplzzz** [comment]
@cledna When we get to a convenient pause point on the other project, we really should get this outstanding issue resolved.

**Comment by rplzzz** [comment]
I tweaked the tests directory a bit.  The test results should never have been committed to the repository, for the reasons I mentioned above, so I removed those, and I updated a few paths to work on PIC.  The tests for the GCAM queries are still flaky, but that's more a function of getting the right combination of versions of GCAM output and the ModelInterface jar.  Since the tests serve their primary purpose of indicating whether your GCAM query setup works, I'm going to call that good enough for now.

**Pull request merged**
